version: '3.8'
services:
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: transpal
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    command: npm run start
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3030:3030"
    depends_on:
      - db

volumes:
  db_data:
