version: '3.8'
services:
  transpal-db:
    container_name: transpal-db
    image: mysql:lts
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: transpal
    ports:
      - "3316:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-uroot", "-prootpassword"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  app:
    build: .
    command: npm run start
    volumes:
      - /app/node_modules
    ports:
      - "3030:3030"
    depends_on:
      transpal-db:
        condition: service_healthy


volumes:
  db_data: